"""add name & price to products

Revision ID: 01d44368a8f3
Revises: 5c9b47c1d269
Create Date: 2025-05-26 10:51:05.368568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d44368a8f3'
down_revision: Union[str, None] = '5c9b47c1d269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
